catalog/urls.py
from django.urls import path
from . import views
from .views import AuthorListView, AuthorDetailView

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>/', AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _  # Import gettext
from django.contrib.auth.models import User
from datetime import date
import uuid  # For unique book instances
import os  # For environment variables


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(
        max_length=int(os.environ.get('GENRE_NAME_MAX_LENGTH')),  
        help_text=_("Enter a book genre (e.g. Science Fiction)"),  
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(
        max_length=int(os.environ.get('BOOK_TITLE_MAX_LENGTH')),  
    )

    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=int(os.environ.get('BOOK_SUMMARY_MAX_LENGTH')), 
        help_text=_("Enter a brief description of the book"), 
    )

    isbn = models.CharField(
        _("ISBN"),
        max_length=int(os.environ.get('BOOK_ISBN_MAX_LENGTH')), 
        unique=True,
        help_text=_('13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'),
    )

    genre = models.ManyToManyField(
        Genre,
        help_text=_("Select a genre for this book"),  
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for Genre. This is required to display genre is Admin."""
        return ','.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_("Unique ID for this particular book across whole library"),
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT)
    imprint = models.CharField(
        max_length=int(os.environ.get('BOOK_INSTANCE_IMPRINT_MAX_LENGTH')),  
    )
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ("m", _("Maintenance")),  
        ("o", _("On loan")),  
        ("a", _("Available")), 
        ("r", _("Reserved")), 
    )
    
    ON_LOAN = "o"
    
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text=_("Book availability"),  
    )

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"
        
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False
        return self.due_back and date.today() > self.due_back


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(
        max_length=int(os.environ.get('AUTHOR_FIRST_NAME_MAX_LENGTH')), 
    )
    last_name = models.CharField(
        max_length=int(os.environ.get('AUTHOR_LAST_NAME_MAX_LENGTH')), 
    )
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(_("Died"), null=True, blank=True) 

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
                    help_text=_("Enter a date between now and 4 weeks (default 3).")
                    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from catalog import constants
from catalog.constants import LOAN_STATUS_LOOKUP
from catalog.models import Book, Author, BookInstance, Genre
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookForm
from catalog.models import BookInstance
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

def index(request):
    """View function for the home page of site."""
    
    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status=LOAN_STATUS_LOOKUP['available']).count()
    num_authors = Author.objects.count()
    
    # Visit count
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits + 1,
    }

    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model               = Book
    paginate_by         = constants.BOOK_LIST_VIEW_PAGINATE
    context_object_name = 'book_list'
    template_name       = 'catalog/book_list.html'


class BookDetailView(generic.DetailView):
    model         = Book
    template_name = 'catalog/book_detail.html'

    def get_context_data(self, **kwargs):
        """Bổ sung thêm danh sách copies và các label trạng thái"""
        context = super().get_context_data(**kwargs)
        book    = self.get_object()
        context['copies']          = book.bookinstance_set.all()
        context['STATUS_AVAILABLE']   = constants.STATUS_AVAILABLE
        context['STATUS_MAINTENANCE'] = constants.STATUS_MAINTENANCE
        context['status_labels']   = dict(constants.LOAN_STATUS)
        return context

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Liệt kê sách user hiện tại đang mượn."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'  
    paginate_by = constants.MY_BORROWED_PAGINATE_BY


    def get_queryset(self):
        return (BookInstance.objects
                .filter(borrower=self.request.user)                         
                .filter(status__exact=constants.STATUS_ON_LOAN)
                .order_by('due_back'))                                      

class AuthorListView(generic.ListView):
    model = Author
    template_name = 'catalog/author_list.html'   
    context_object_name = 'author_list'
    paginate_by = constants.AUTHOR_LIST_VIEW_PAGINATE


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""

    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': constants.DEFAULT_DATE_OF_DEATH}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>{% trans "Delete Author" %}</h1>
  <p>{% trans "Are you sure you want to delete the author:" %} {{ author }}?</p>
  <form method="post">{% csrf_token %}
    <input type="submit" value="{% trans "Yes, delete" %}">
  </form>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{{ view.title }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="{% trans "Submit" %}">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Author List" %}</h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{% url 'author-detail' author.pk %}">
            {{ author.last_name }}, {{ author.first_name }}
          </a>
        </li>
      {% endfor %}
    </ul>
    {# nếu paginate_by, thêm điều khiển phân trang ở đây #}
  {% else %}
    <p>{% trans "There are no authors in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Title" %}: {{ book.title }}</h1>
    
    <p><strong>{% trans "Author" %}:</strong> <a href="">{{ book.author }}</a></p>
    <p><strong>{% trans "Summary" %}:</strong> {{ book.summary }}</p>
    <p><strong>{% trans "ISBN" %}:</strong> {{ book.isbn }}</p>
    <p><strong>{% trans "Language" %}:</strong> {{ book.language }}</p>
    <p><strong>{% trans "Genre" %}:</strong> {{ genre_list|join:", " }}</p>

    <div class="book-copies">
        <h4>{% trans "Copies" %}</h4>
    
        {% for copy in book_instances %}
            <hr>
            <p class="{% if copy.status == status_labels.available %}text-success
                       {% elif copy.status == status_labels.maintenance %}text-danger
                       {% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != status_labels.available %}
                <p><strong>{% trans "Due to be returned" %}:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>{% trans "Imprint" %}:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>{% trans "Id" %}:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Book List" %}</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>{% trans "There are no books in the library." %}</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}
  <h1>{% trans "Renew:" %} {{ book_instance.book.title }}</h1>
  <p><strong>{% trans "Borrower" %}:</strong> {{ book_instance.borrower }}</p>
  {% if book_instance.is_overdue %}
    <p class="text-danger">{% trans "Overdue" %}</p>
  {% endif %}
  <p><strong>{% trans "Due date" %}:</strong> {{ book_instance.due_back }}</p>
  <form method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="{% trans "Submit" %}">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "My Borrowed Books" %}</h1>

  {% if bookinstance_list %}
    <ul>
      {% for inst in bookinstance_list %}
        <li class="{% if inst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' inst.book.pk %}">
            {{ inst.book.title }}
          </a> — {{ inst.due_back }}
        </li>
      {% endfor %}
    </ul>

  {% else %}
    <p>{% trans "You have no books on loan." %}</p>
  {% endif %}
{% endblock %}